### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by marcelsavegnago** [Escodoo/account-addons#38]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [x] account_move_change_financial_account
- [x] account_move_line_cash_basis_report
- [x] mis_builder_cash_flow_by_month
- [x] mis_builder_cash_flow_forecast_contract
- [x] mis_builder_cash_flow_forecast_integration
- [x] mis_builder_cash_flow_forecast_purchase
- [x] mis_builder_cash_flow_forecast_sale
- [x] mis_builder_cash_flow_forecast_sale_invoice_plan
- [x] sync_multi_company_bank_account

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
