### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by marcelsavegnago** [Escodoo/account-addons#44]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_asset_classification #103 
- [x] account_bank_statement_internal_transfer #135
- [x] account_compensate_advance https://github.com/OCA/account-invoicing/pull/1964
- [x] account_compensate_advance_unlock_reconcile #128
- [ ] account_compensate_advance_unlock_reconcile_journal #136
- [x] account_group_disable_adapt_methods #116 
- [x] account_move_change_financial_account #162 
- [X] account_move_line_cash_basis_report #52 
- [x] account_move_visible_date_maturity #111 
- [x] account_payment_other_company_custom_ref - Tem que vê questão do modulo `account_payment_other_company` que foi descontinuado
- [x] account_reconciliation_widget_order_by_desc - Modulo `account_reconciliation_widget` foi descontinuado. #164
- [x] account_statement_import_ofx_unique_import_id #129
- [x] analytic_restrictions #149 
- [x] hr_timesheet_analytic_restrictions #114 
- [x] l10n_br_account_service_type_by_partner #99
- [x] l10n_br_mis_builder_cash_flow_sale #161 
- [x] l10n_br_trade_import #126
- [x] mis_builder_cash_flow_by_month #120 
- [x] mis_builder_cash_flow_forecast_contract #146
- [x] mis_builder_cash_flow_forecast_integration #117 
- [x] mis_builder_cash_flow_forecast_purchase #160
- [x] mis_builder_cash_flow_forecast_sale #150 
- [x] mis_builder_cash_flow_forecast_sale_invoice_plan #163
- [x] mis_builder_custom_reports #157 
- [x] mis_builder_kpi_code #147 
- [x] sale_analytic_restrictions #115 
- [x] sync_multi_company_bank_account #148

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
